
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#535965"
blue = "#4fa6ed"
cyan = "#48b0bd"
green = "#8ebd6b"
magenta = "#bf68d9"
red = "#e55561"
white = "#b2bbcc"
yellow = "#e2b86b"

[colors.normal]
black = "#0e1013"
blue = "#4fa6ed"
cyan = "#48b0bd"
green = "#8ebd6b"
magenta = "#bf68d9"
red = "#e55561"
white = "#b2bbcc"
yellow = "#e2b86b"

[colors.primary]
background = "#1f2329"
foreground = "#b2bbcc"

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[scrolling]
history = 3000

[terminal.shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10

[general]
live_config_reload = true

[terminal]
